[package]
name = "core-math"
version = "1.1.1"
authors = ["Chen-Pang He (https://jdh8.org)"]
edition = "2024"
rust-version = "1.85"
description = "Rusty API for CORE-MATH"
repository = "https://github.com/jdh8/core-math"
license = "MIT"
categories = ["mathematics", "no-std"]
keywords = ["floating-point", "trigonometry", "exponential", "logarithm", "special-functions"]
autobenches = false

[features]
f16 = ["core-math-sys/f16"]
f128 = ["core-math-sys/f128"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
core-math-sys = "1.1.1"

[dev-dependencies]
criterion = "0.8"
libm = "0.2"
rand = "0.10"

[profile.dev]
opt-level = 3

[[bench]]
name = "acos"
harness = false

[[bench]]
name = "acosf"
harness = false

[[bench]]
name = "acosh"
harness = false

[[bench]]
name = "acoshf"
harness = false

[[bench]]
name = "asin"
harness = false

[[bench]]
name = "asinf"
harness = false

[[bench]]
name = "asinh"
harness = false

[[bench]]
name = "asinhf"
harness = false

[[bench]]
name = "atan"
harness = false

[[bench]]
name = "atan2"
harness = false

[[bench]]
name = "atan2f"
harness = false

[[bench]]
name = "atanf"
harness = false

[[bench]]
name = "atanh"
harness = false

[[bench]]
name = "atanhf"
harness = false

[[bench]]
name = "cbrt"
harness = false

[[bench]]
name = "cbrtf"
harness = false

[[bench]]
name = "compoundf"
harness = false

[[bench]]
name = "cos"
harness = false

[[bench]]
name = "cosf"
harness = false

[[bench]]
name = "cosh"
harness = false

[[bench]]
name = "coshf"
harness = false

[[bench]]
name = "erf"
harness = false

[[bench]]
name = "erfc"
harness = false

[[bench]]
name = "erfcf"
harness = false

[[bench]]
name = "erff"
harness = false

[[bench]]
name = "exp"
harness = false

[[bench]]
name = "exp10"
harness = false

[[bench]]
name = "exp10f"
harness = false

[[bench]]
name = "exp2"
harness = false

[[bench]]
name = "exp2f"
harness = false

[[bench]]
name = "expf"
harness = false

[[bench]]
name = "expm1"
harness = false

[[bench]]
name = "expm1f"
harness = false

[[bench]]
name = "hypot"
harness = false

[[bench]]
name = "hypotf"
harness = false

[[bench]]
name = "lgamma"
harness = false

[[bench]]
name = "lgammaf"
harness = false

[[bench]]
name = "log"
harness = false

[[bench]]
name = "log10"
harness = false

[[bench]]
name = "log10f"
harness = false

[[bench]]
name = "log1p"
harness = false

[[bench]]
name = "log1pf"
harness = false

[[bench]]
name = "log2"
harness = false

[[bench]]
name = "log2f"
harness = false

[[bench]]
name = "logf"
harness = false

[[bench]]
name = "pow"
harness = false

[[bench]]
name = "powf"
harness = false

[[bench]]
name = "sin"
harness = false

[[bench]]
name = "sincos"
harness = false

[[bench]]
name = "sincosf"
harness = false

[[bench]]
name = "sinf"
harness = false

[[bench]]
name = "sinh"
harness = false

[[bench]]
name = "sinhf"
harness = false

[[bench]]
name = "tan"
harness = false

[[bench]]
name = "tanf"
harness = false

[[bench]]
name = "tanh"
harness = false

[[bench]]
name = "tanhf"
harness = false

[[bench]]
name = "tgamma"
harness = false

[[bench]]
name = "tgammaf"
harness = false
